# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Golang image to create a build artifact.
FROM golang:1.21 as builder

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Build the Go app
RUN go build -o axiom-mcp

# Start a new stage from scratch
FROM debian:bookworm-slim

# Set environment variables
ENV AXIOM_TOKEN=xaat-your-token
ENV AXIOM_URL=https://api.axiom.co
ENV AXIOM_ORG_ID=your-org-id
ENV AXIOM_QUERY_RATE=1
ENV AXIOM_QUERY_BURST=1
ENV AXIOM_DATASETS_RATE=1
ENV AXIOM_DATASETS_BURST=1

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy the Pre-built binary file from the previous stage
COPY --from=builder /app/axiom-mcp .

# Command to run the executable
ENTRYPOINT ["./axiom-mcp"]